### ISSUE TITLE
Failing plot (TLF issue)

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR.reports#6]
With latest branch, executing https://github.com/esqLABS/esqlabsR.reports/blob/main/tests/test-export-failing.R:

`Error: The function textbox_grob() is not vectorized.`

**Comment by Felixmil** [comment]
This is caused by ospsuite which calls a method that does not exist anymore (name changed). I created a branch on ospsuite to fix this. What is concerning is that none of the tlf or ospsuite tests broke (except slight change in vignettes), I guess we need better code coverage on these packages.

**Comment by Felixmil** [comment]
The probleme here happens to be that the title's text is a vector of 3 strings:

```
newPlotObject$plotConfiguration$labels$title$text
[1] "Antecip Bioventures EM"                                              
[2] "60 mg dextromethorphan hydrobromide multiple dose (capsule/solution)"
[3] "n=10"
```
And ggtext::element_textbox() cannot apply on a vector:

```r
newPlotObject +ggplot2::labs(title = newPlotObject$plotConfiguration$labels$title$text) +  ggplot2::theme(plot.title = newPlotObject$plotConfiguration$labels$title$createPlotTextBoxFont())
Error: The function textbox_grob() is not vectorized.
```

However, if we collapse the vector:
```r
newPlotObject +ggplot2::labs(title = paste(newPlotObject$plotConfiguration$labels$title$text, collapse = ", ")) +  ggplot2::theme(plot.title = newPlotObject$plotConfiguration$labels$title$createPlotTextBoxFont())
```
It works:
![image](https://github.com/esqLABS/esqlabsR.reports/assets/34234913/33397d94-7dd7-43b5-a02c-42f3cf55434d)

So I have these questions for you @PavelBal :
  1. Is this normal that the title's text is a vector in this case ?
  2. Is it ok that if a vector is passed as text, we always paste it with collapse = ", " ?

**Comment by PavelBal** [comment]
I had to apply the same workaround in the PR for scaling. I have NO IDEA why the title is a vector, in the PlotConfiguration it is one string and I did not find (to be honest, I did not track far) when the string gets split.

**Comment by PavelBal** [comment]
OK sorry, I think I know why...

**Comment by PavelBal** [comment]
@Felixmil my bad, title colume was split during plot configuration creation in esqlabsR. This PR fixes it: https://github.com/esqLABS/esqlabsR/pull/509

**Comment by PavelBal** [comment]
Fixed.
